### ISSUE TITLE
Song info difficulty is doubled in v5 (Bug/Feature)

### ISSUE THREAD

**Issue by t404owo** [ReiKohaku/BotArcApi_lib#6]
Instead of showing this (output of v4):
```json
{
"song_id":"any_track",
"difficulties": [
    {    
        ...
        "difficulty": 4,
        ...
    }
]
}
```
the output of the current version (v1.1.8) in v5 shows the following...:
```json
{
"song_id":"any_track",
[
    {    
        ...
        "difficulty": 8,//(which is doubled)
        ...
    }
]
}
```
Is this a feature? Or else can you please fix this problem for the next version?

**Comment by bsdayo** [comment]
This is a feature in the new songinfo format of ArcaeaUnlimitedAPI. When the difficulty is an odd number, it means the ingame difficulty have a plus sign.

For example:
```json
{
    "name_en": "Ringed Genesis",
    ...
    "difficulty": 21,    // means 10+
    ...
}
```

**Comment by bsdayo** [comment]
Is there any other question? If not I'll close this issue :)
